heat_template_version: 2013-05-23

description: AWS SecurityGroup with Neutron

parameters:
    network:
      type: string
      description: ID of the netowrk for Security Group

resources:
  SecurityGroup:
    type: AWS::EC2::SecurityGroup
    properties:
      GroupDescription: Test AWS SecGroup Neutron
      VpcId: { get_param: network }
      SecurityGroupEgress:
      - CidrIp: '0.0.0.0/24'
        FromPort: '8888'
        ToPort: '8888'
        IpProtocol: 'tcp'
      SecurityGroupIngress:
      - CidrIp: '0.0.0.0/24'
        FromPort: '8888'
        ToPort: '8888'
        IpProtocol: 'tcp'

outputs:
  rules:
    description: Rules belonging to the security group
    value: { get_attr: [SecurutyGroup, Rules] }
