heat_template_version: 2013-05-23

parameters:
  console_type:
    type: string
    default: xvpvnc

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: cirros-0.3.2-x86_64-uec
      flavor: m1.nano

outputs:
  console:
    description: Console for server
    value:
      get_attr:
      - server
      - console_urls
      - get_param: console_type
