heat_template_version: 2014-10-16

description:  AWS Load Balancer balancing HTTP connections

parameters:
  
  KeyName:
    type: string
    default: demo

  image:
    type: string
    default: Fedora-x86_64-20-20140618-sda

  flavor:
    type: string
    default: m1.heat

  size:
    type: number
    default: 2

  port_lb:
    type: string
    default: '80'

  port_app:
    type: string
    default: '8000'

resources:

  config:
    type: AWS::AutoScaling::LaunchConfiguration
    properties:
      KeyName: { get_param: KeyName }
      ImageId: { get_param: image }
      InstanceType: { get_param: flavor }
      UserData:
        str_replace:
          template: |
            #!/bin/bash -v
            echo $(hostname) > index.html
            echo $(hostname -i) >> index.html
            python -m SimpleHTTPServer PORT
          params:
            PORT: { get_param: port_app }

  group:
    type: OS::Heat::InstanceGroup
    properties:
      AvailabilityZones:
        - nova
      LaunchConfigurationName: { get_resource: config }
      LoadBalancerNames: [ { get_resource: aws_lb }, ]
      Size: { get_param: size }

  aws_lb:
    type: AWS::ElasticLoadBalancing::LoadBalancer
    properties:
      AvailabilityZones:
        - nova
      Listeners:
        - LoadBalancerPort: { get_param: port_lb }
          InstancePort: { get_param: port_app }
          Protocol: HTTP

outputs:
  app:
    description: loadbalanced app URL
    value:
      str_replace:
        template: http://IPADDRESS:PORT
        params:
          IPADDRESS: { get_attr: [ aws_lb, DNSName ] }
          PORT: { get_param: port_lb }
