heat_template_version: 2013-05-23

description: Pool with Health monitors.

resources:
  HealthMon1:
    type: OS::Neutron::HealthMonitor
    properties:
      delay: 60
      timeout: 10
      max_retries: 2
      type: PING
  HealthMon2:
    type: OS::Neutron::HealthMonitor
    properties:
      delay: 60
      timeout: 10
      max_retries: 2
      type: PING
  Pool:
    type: OS::Neutron::Pool
    properties:
      lb_method: ROUND_ROBIN
      protocol: TCP
      subnet_id: 92872f7e-dcc3-45b3-9f2e-76ff3a0a1165
      vip:
        protocol_port: 22
      monitors: [ { get_resource: HealthMon2 } ]
