heat_template_version: 2013-05-23

description: Pool with Health monitors.

resources:
  HealthMon1:
    type: OS::Neutron::HealthMonitor
    properties:
      delay: 60
      timeout: 10
      max_retries: 2
      type: PING
  HealthMon2:
    type: OS::Neutron::HealthMonitor
    properties:
      delay: 60
      timeout: 10
      max_retries: 2
      type: PING
  Pool:
    type: OS::Neutron::Pool
    properties:
      lb_method: ROUND_ROBIN
      protocol: TCP
      subnet_id: b69416f3-d612-459b-84d6-9f1dd210a16a
      vip:
        protocol_port: 22
      monitors: [ { get_resource: HealthMon2 } ]
