heat_template_version: 2013-05-23

resources:
  LoadBalancer:
    type: AWS::ElasticLoadBalancing::LoadBalancer
    properties:
      AvailabilityZones: {'Fn::GetAZs': ''}
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      HealthCheck:
        Target: 'HTTP:80/'
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
