heat_template_version: 2013-05-23
description: Instance creation template for {{datastore_manager}}
parameters:
  Flavor:
    type: string
    default: m1.heat
  Key:
    type: string
    default: demo
  ImageId:
    type: string
    default: Fedora-x86_64-20-20140618-sda
  AvailabilityZone:
    type: string
    default: nova
  userparam:
    type: string
    default: SomeMoreData

resources:

  BaseConfig:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /etc/check.conf
          owner: root:root
          permissions: '0644'
          content:
            str_replace:
              template: |
                [DEFAULT]
                param = $USERPARAM
              params:
                $USERPARAM: { get_param: userparam }
        runcmd:
          whoami > /home/fedora/whowasi.txt

  BaseInstance:
    type: OS::Nova::Server
    properties:
      image: { get_param: ImageId }
      flavor: { get_param: Flavor }
      key_name: { get_param: Key }
      availability_zone: { get_param: AvailabilityZone }
      user_data_format: RAW
      user_data: { get_resource: BaseConfig }
