heat_template_version: 2013-05-23

description: >
  HOT template that creates a nova instance, a cinder volumes and attaches
  the volumes to the instance.

parameters:
  flavor:
    type: string
    description: Instance type for the instance to be created
    default: m1.nano
    constraints:
      - allowed_values: [m1.nano, m1.micro, m1.tiny]
        description: Value must be one of 'm1.nano', 'm1.micro', 'm1.tiny'.
  image:
    type: string
    description: name of the image to use for the instance
    default: cirros-0.3.1-x86_64-disk 
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
    default: nova
  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 1
    constraints:
      - range: { min: 1, max: 1024 }
        description: must be between 1 and 1024 Gb.
  mount:
    type: string
    description: mountpoint for a volume on a server
    default: /dev/vdc

resources:
  instance:
    type: OS::Nova::Server
    properties:
      availability_zone: { get_param: availability_zone }
      image: { get_param: image }
      flavor: { get_param: flavor }
  volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }
      availability_zone: { get_param: availability_zone }
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_resource: instance }
      mountpoint: { get_param: mount }

outputs:
  instance_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [instance, first_address] }
  volume_size:
    description: Size of the volume
    value: { get_attr: [volume, size] }
