heat_template_version: 2013-05-23

description: >
  HOT template that creates one instance and attaches an existing cinder volume to it.

parameters:
  volume:
    type: string
    description: ID of the volume to attach
  device:
    type: string
    description: mountpoint for the volume
    default: '/dev/vdc'
    
resources:
  nova_instance:
    type: OS::Nova::Server
    properties:
      availability_zone: nova
      image: cirros-0.3.1-x86_64-disk
      flavor: m1.nano
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: nova_instance }
      volume_id: { get_param: volume }
      mountpoint: { get_param: device }

outputs:
  instance_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [nova_instance, first_address] }
