heat_template_version: 2013-05-23
description: Test for CloudConfig resource
parameters:
  Flavor:
    type: string
    default: m1.heat
  Key:
    type: string
    default: demo
  ImageId:
    type: string
    default: Fedora-x86_64-20-20140618-sda
  AvailabilityZone:
    type: string
    default: nova
  PublicNet:
    type: string
    default: public
  PrivateNet:
    type: string
    default: private
  userparam:
    type: string
    default: SomeMoreData

resources:

  Port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: PrivateNet }

  BaseConfig:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /etc/check.conf
          owner: root:root
          permissions: '0644'
          content:
            str_replace:
              template: |
                [DEFAULT]
                param = $USERPARAM
              params:
                $USERPARAM: { get_param: userparam }
        runcmd:
          - whoami > /home/fedora/whowasi.txt

  BaseInstance:
    type: OS::Nova::Server
    properties:
      image: { get_param: ImageId }
      flavor: { get_param: Flavor }
      key_name: { get_param: Key }
      availability_zone: { get_param: AvailabilityZone }
      networks:
        - port: { get_resource: Port }
      user_data_format: RAW
      user_data: { get_resource: BaseConfig }

  FloatIP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: PublicNet }

  FloatIPassoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: FloatIP }
      port_id: { get_resource: Port }

outputs:
  PublicIP:
    description: Public IP of the instance
    value: { get_attr: [ BaseInstance,  networks, { get_param: PrivateNet }, 1 ] }
