heat_template_version: 2015-10-15

description: |
  Simplest webapp using netcat (custom fit for CirrOS).

parameters:
  curl_cli:
    type: string
  port:
    type: number

resources:
  config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: |
            #! /bin/sh -v
            Body=$(cat /etc/hostname)
            Response="HTTP/1.1 200 OK\r\nContent-Length: ${#Body}\r\n\r\n$Body"
            echo $Response
            echo "while true ; do echo -e \"${Response}\" | nc -llp PORT; done" > /bin/ncserve
            chmod +x /bin/ncserve
            #(sudo ncserve > /dev/null 2>&1 &) &
            wc_notify --data-binary '{"status": "SUCCESS"}'
            nohup ./bin/ncserve > /dev/null 2>&1 &
          params:
            wc_notify: { get_param: curl_cli }
            PORT: { get_param: port }

outputs:
  OS::stack_id:
    value: { get_resource: config }
