heat_template_version: 2013-05-23

description: >
  Heat template that brings up a stack of two instances, one with Tomcat
  and another with PostgreSQL installed.

parameters:

  key_name:
    type: string
    description : Name of a KeyPair to enable SSH access to the instance
  instance_type_tomcat:
    type: string
    description: Instance type for Tomcat server
    default: m1.tiny
    constraints:
      - allowed_values: [m1.tiny, m1.small, m1.medium, m1.large]
        description: instance_type must be one of m1.tiny, m1.small, m1.medium or m1.large
  instance_type_postgres:
    type: string
    description: Instance type for PostgreSQL server
    default: m1.tiny
    constraints:
      - allowed_values: [m1.tiny, m1.small, m1.medium, m1.large]
        description: instance_type must be one of m1.tiny, m1.small, m1.medium or m1.large
  image_id_tomcat:
    type: string
    description: ID of the image to use for the Tomcat server
    default: F19-x86_64-cfntools
    constraints:
      - allowed_values: [ F19-i386-cfntools, F19-x86_64-cfntools ]
        description: >
          Image ID must be either F19-i386-cfntools or F19-x86_64-cfntools
  image_id_tomcat:
    type: string
    description: ID of the image to use for the PostgreSQL server
    default: F19-x86_64-cfntools
    constraints:
      - allowed_values: [ F19-i386-cfntools, F19-x86_64-cfntools ]
        description: >
          Image ID must be either F19-i386-cfntools or F19-x86_64-cfntools
  db_name:
    type: string
    description: Postgres database name
    default: postgres
    constraints:
      - length: { min: 1, max: 64 }
        description: db_name must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_name must begin with a letter and contain only alphanumeric
          characters
  db_username:
    type: string
    description: The Postgres database admin account username
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 16 }
        description: db_username must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_username must begin with a letter and contain only alphanumeric
          characters
  db_password:
    type: string
    description: The Postgres database admin account password
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_username must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_password must contain only alphanumeric characters
  db_root_password:
    type: string
    description: Root password for PostgresSQL
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_username must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_password must contain only alphanumeric characters
  some_param:
    type: string
    description: some parameter
    default: ''
    
resources:
  tomcat_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id_tomcat }
      flavor: { get_param: instance_type_tomcat }
      key_name: { get_param: key_name }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            
            yum install -y some_param
          params:
            some_param: { get_param: some_param }
  postgres_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id_postgres }
      flavor: { get_param: instance_type_postgres }
      key_name: { get_param: key_name }
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v

            yum -y install mysql mysql-server httpd wordpress
            systemctl enable mysqld.service
            systemctl enable httpd.service
            systemctl start mysqld.service
            systemctl start httpd.service

            firewall-cmd --add-service=http
            firewall-cmd --permanent --add-service=http

            # Setup MySQL root password and create a user
            mysqladmin -u root password db_rootpassword
            cat << EOF | mysql -u root --password=db_rootpassword
            CREATE DATABASE db_name;
            GRANT ALL PRIVILEGES ON db_name.* TO "db_user"@"localhost"
            IDENTIFIED BY "db_password";
            FLUSH PRIVILEGES;
            EXIT
            EOF

            sed -i "/Deny from All/d" /etc/httpd/conf.d/wordpress.conf
            sed -i "s/Require local/Require all granted/" /etc/httpd/conf.d/wordpress.conf
            sed -i s/database_name_here/db_name/ /etc/wordpress/wp-config.php
            sed -i s/username_here/db_user/ /etc/wordpress/wp-config.php
            sed -i s/password_here/db_password/ /etc/wordpress/wp-config.php

            systemctl restart httpd.service
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }

outputs:
  Postgres_IP:
    description: IP of Postgres instance
    value: { get_attr: [postgres_instance, first_address] }
  Tomcat_IP:
    description: IP of Tomcat instance
    value: { get_attr: [tomcat_instance, first_address] }
