heat_template_version: 2013-05-23
Description: >
  Heat Tomcat + PostgreSQL template

resources:
  databaseServer:
    type: OS::Nova::Server
    properties:
      image: F18-x86_64-cfntools
        flavor: m1.medium
        key_name: mykey
        user_data: |
          #!/bin/bash -v
          
          yum -y install postgresql-server postgresql-contrib
          postgresql-setup initdb
          systemctl enable postgresql.service  
          systemctl start postgresql.service  
    
  applicationServer:
    type: OS::Nova::Server
    properties:
      image: F18-x86_64-cfntools
      flavor: m1.medium
      key_name: mykey
      user_data: |
        #!/bin/bash -v
                         
        yum -y install tomcat tomcat-webapps tomcat-admin-webapps
        systemctl enable tomcat.service  
        systemctl start tomcat.service

  waitHandle: 
    type: AWS::CloudFormation::WaitConditionHandle
  
  waitCondition:
    type: AWS::CloudFormation::WaitCondition
    depends_on: applicationServer
    properties:
      Handle: {get_resource:  waitHandle}
      Count: 1
      Timeout: 600

outputs:
  applicationServerIp:
    description: URL for application server
    value: { get_attr: [applicationServer, first_address] }
