heat_template_version: 2013-05-23

description: >
  HOT template - deploys server with user-provided name, image, key, flavor
  Attaches to private Neutron network, and obtains floating IP on public network
  Sets SecurityGroup to allow pinging and SSH access
      
parameters:
  server_name:
    type: string
    description: Name of your new server
    default: MyServer
  key_name:
    type: string
    description: Keypair name
    default: demo
  image:
    type: string
    description: Image name
    default: cirros-0.3.2-x86_64-uec
  flavor:
    type: string
    description: Flavor
    default: m1.nano
    constraints:
      - allowed_values:
        - m1.nano
        - m1.heat
        - m1.tiny
        - m1.small
  public_net:
    type: string
    description: Name or ID of the external network
    default: public
  private_net:
    type: string
    description: Name or ID of the internal network
    default: private

resources:

  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server_port }

  server_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_net }
      security_groups:
        - get_resource: server_security_group

  server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: server_port }

  server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for server
      name: security-group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

outputs:
  server_private_ip:
    description: IP address of server on private network
    value:
      get_attr:
      - server
      - first_address
  server_public_ip:
    description: Floating IP address of server on public network
    value:
      get_attr:
      - server_floating_ip
      - floating_ip_address
