heat_template_version: 2013-05-23
description: As reported by Murano

resources:

  server:
    type: OS::Nova::Server
    properties:
      user_data_format: HEAT_CFNTOOLS
      image: cirros
      flavor: m1.nano
      security_groups:
      - { get_resource: secgroup }
      
  flipassign:
    type: OS::Nova::FloatingIPAssociation
    properties:
      server_id: { get_resource: server }
      floating_ip: { get_resource: flip }

  flip:
    type: OS::Nova::FloatingIP

  secgroup:
    type: AWS::EC2::SecurityGroup
    properties:
      GroupDescription: Composite security group
      SecurityGroupIngress: 
      - ToPort: '-1'
        FromPort: '-1'
        CidrIp: 0.0.0.0/0
        IpProtocol: icmp
      - ToPort: '23'
        FromPort: '23'
        IpProtocol: tcp
        CidrIp: 0.0.0.0/0
      - ToPort: '22'
        FromPort: '22'
        IpProtocol: tcp
        CidrIp: 0.0.0.0/0

outputs:
    floatingIPaddress:
      value: { get_attr: [flip, ip ] }
      description: Floating IP assigned
    server-ip: 
      description: IP address assigned to server
      value: { get_attr: [ server, addresses ] }
